# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Domain\Credit\Modifiers\OstravaClientRateModifier:
        tags: ['credit_modifier']

    App\Domain\Credit\Rules\ClientMinimumScoreRule:
        tags: ['credit_application_rule']
    App\Domain\Credit\Rules\ClientMinimumIncomeRule:
        tags: ['credit_application_rule']
    App\Domain\Credit\Rules\ClientValidAgeRule:
        tags: ['credit_application_rule']
    App\Domain\Credit\Rules\ClientValidRegionRule:
        tags: ['credit_application_rule']
    App\Domain\Credit\Rules\PragueRandomPassRule:
        tags: ['credit_application_rule']

    App\Notifiers\LogNotifier:
        arguments:
            $logger: '@monolog.logger.credit'

    App\Repositories\ClientRepository:
        arguments:
            $filePath: '%kernel.project_dir%/var/storage/clients.json'
    App\Repositories\CreditRepository:
        arguments:
            $storageDirectory: '%kernel.project_dir%/var/storage'

    App\Services\ApplicationService:
        arguments:
            $storageDirectory: '%kernel.project_dir%/var/storage'
    App\Services\GiveCreditService:
        arguments:
            $rules: !tagged_iterator credit_application_rule
            $modifiers: !tagged_iterator credit_modifier

    App\Validators\ExistingPinValidator:
        arguments:
            - '@App\Repositories\ClientRepository'
        tags: [validator.constraint_validator]
    App\Validators\UniquePinValidator:
        arguments:
            - '@App\Repositories\ClientRepository'
        tags: [validator.constraint_validator]
